spring.application.name=Take_Home_Exercise

# MySQL Database Settings
spring.datasource.url=jdbc:mysql://localhost:3306/HomeExercise_db
spring.datasource.username=root
spring.datasource.password=kishan@8084

# Specify the MySQL dialect for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# This tells Hibernate to update the table schema automatically if the @Entity class changes
spring.jpa.hibernate.ddl-auto=update
# Prints SQL queries to the console for debugging
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
