version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-product-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kishan@8084
      MYSQL_DATABASE: HomeExercise_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  product-importer-app:
    build: .
    container_name: product-importer-app
    restart: on-failure
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/HomeExercise_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kishan@8084
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
